version: '3'
services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "9080:9080"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: moany
      MYSQL_USER: moany
      MYSQL_PASSWORD: password
    ports:
      - "3336:3306"
    volumes:
      - "/home/alunwcom/mysql:/var/lib/mysql"
