---

spring.datasource.url: "jdbc:mysql://localhost:3306/moany?verifyServerCertificate=false&useSSL=true"
spring.datasource.username: "moany"
spring.datasource.password: "mushroom"
spring.jpa.database-platform: "MySQL8"

logging.level.com.alunw: DEBUG

