---
server.port: 9080

logging.file: moany.log
logging.file.max-history: 5
logging.file.max-size: 10MB

moany.homeFolder: ""
#moany.admin.username: admin
#moany.admin.password: password

server.tomcat.basedir: .

# Locations of static resources.
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/angular/

#spring.datasource.url: jdbc:h2:mem:moany
#spring.datasource.username: sa
#spring.datasource.password: password
#spring.jpa.database-platform: H2

#spring.datasource.url: jdbc:mysql://localhost:3336/moany?verifyServerCertificate=false&useSSL=true
#spring.datasource.username: moany
#spring.datasource.password: password
#spring.jpa.database-platform: MySQL8

#moany:
#  databaseStartupInterval: 5
#  databaseStartupTimeout: 120

spring.datasource.url: jdbc:h2:mem:moany
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: H2

#spring.datasource.url: jdbc:mysql://localhost:3336/moany?verifyServerCertificate=false&useSSL=true
#spring.datasource.username: moany
#spring.datasource.password: password
#spring.jpa.database-platform: MySQL8

server:
  error:
    path: /error
    whitelabel.enabled: false

# none This is the default for MySQL, no change to the database structure.
# update Hibernate changes the database according to the given Entity structures.
# create Creates the database every time, but don’t drop it when close.
# create-drop Creates the database then drops it when the SessionFactory closes.
# validate: validate the schema, makes no changes to the database.
#spring.jpa.hibernate.ddl-auto: create-drop

#spring.jpa.properties.hibernate.show_sql: true
#spring.jpa.properties.hibernate.use_sql_comments: true
#spring.jpa.properties.hibernate.format_sql: true

#spring.resources.static-locations: file:/css/**,file:/js/**,file:/templates/**
#spring.resources.static-locations: classpath:/resources/*
#spring.mvc.static-path-pattern: /resources/**

spring.freemarker.template-loader-path: classpath:/freemarker
spring.freemarker.suffix: .ftl
spring.freemarker.requestContextAttribute: rc

spring.servlet.multipart.max-file-size: 128KB
spring.servlet.multipart.max-request-size: 128KB

logging.level.com.alunw: DEBUG
#logging.level.org.springframework.security: DEBUG

