---

spring.datasource.url: "jdbc:mysql://db:3306/moany?verifyServerCertificate=false&useSSL=true"
spring.datasource.username: "moany"
spring.datasource.password: "password"
spring.jpa.database-platform: "MySQL8"

logging.level.com.alunw: DEBUG

